In [ ]:
# function transformer
#The function transformer is a tool in scikit learn a popular python libraray
#for machine learning that allows tou to apply a spcified function to the input
#data . The function transformer can be useful for performing custom
# transformations of input data in a machine learning pipeline

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np


In [ ]:
#create a data set
x=np.array([[1,2],[3,4]])

In [ ]:
# define the transformation function
log_transform=FunctionTransformer(np.log1p)

In [ ]:
#apply the transformation to the the data set
x_transformed=log_transform.transform(x)

In [ ]:
#view the transform data
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [ ]:
#create a data set
x=np.array([[1,2],[3,4]])

In [ ]:
#define a custom feature engineering function
def squ(x):
  return np.hstack((x,x**2))

In [ ]:
#create a function transformer to apply the custom function
custom_transformer=FunctionTransformer(squ)

In [ ]:
#apply the transformer to the input data
x_transformed=custom_transformer.transform(x)

In [ ]:
#view the transformed data
print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [ ]:
#create a data set
x=np.array([[1,2],[3,4]])

In [ ]:
#define custom scaling function
def my_scaling(x):
  return x/np.max(x)


In [ ]:
#create a function transformer to apply the custom function
custom_transformer=FunctionTransformer(my_scaling)

In [ ]:
#apply the transformer to the data set
x_transformed=custom_transformer.transform(x)

In [ ]:
#view the transformed data
print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
#create a data set with missing values
x=np.array([[1,2],[3,np.nan]])

In [ ]:
#define custom cleaning function
def my_cleaning(x):
  x[np.isnan(x)]=0
  return x

In [ ]:
#create a function transformer to apply the custom function
custom_transformer=FunctionTransformer(my_cleaning)

In [ ]:
#apply the transformer to the input data set
x_transformed=custom_transformer.transform(x)

In [ ]:
#view the transformed data
print(x_transformed)

[[1. 2.]
 [3. 0.]]


In [ ]:
import pandas as pd


In [ ]:
df=pd.read_csv("/content/newplacementdata - newplacementdata.csv")

In [ ]:
df

cgpa  placement_exam_marks  placed
0    7.19                    26       1
1    7.46                    38       1
2    7.54                    40       1
3    6.42                     8       1
4    7.23                    17       0
..    ...                   ...     ...
995  8.87                    44       1
996  9.12                    65       1
997  4.89                    34       0
998  8.62                    46       1
999  4.90                    10       1

[1000 rows x 3 columns]

In [ ]:
x=df.drop(columns=['placement_exam_marks'])
y=df['placement_exam_marks']

In [ ]:
log_transform=FunctionTransformer(np.log1p)
#apply the transformation to the dataset
x_transformed=log_transform.transform(x)
print(x_transformed)

         cgpa    placed
0    2.102914  0.693147
1    2.135349  0.693147
2    2.144761  0.693147
3    2.004179  0.693147
4    2.107786  0.000000
..        ...       ...
995  2.289500  0.693147
996  2.314514  0.693147
997  1.773256  0.000000
998  2.263844  0.693147
999  1.774952  0.693147

[1000 rows x 2 columns]


In [ ]:
df=pd.read_csv("/content/insurance - insurance.csv")

In [ ]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
x=df.drop(columns=['charges'])
y=df['charges']

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder()

In [ ]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)
x_new=ohe.fit_transform(df[['sex','smoker','region']])

In [ ]:
x_new

array([[0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0],
       ...,
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0]], dtype=int32)

In [ ]:
log_transform=FunctionTransformer(np.log1p)
#apply the transformation to the dataset
x_new_transformed=log_transform.transform(x_new)
print(x_new_transformed)

[[0.         0.69314718 0.         0.         0.69314718]
 [0.69314718 0.         0.         0.69314718 0.        ]
 [0.69314718 0.         0.         0.69314718 0.        ]
 ...
 [0.         0.         0.         0.69314718 0.        ]
 [0.         0.         0.         0.         0.69314718]
 [0.         0.69314718 0.69314718 0.         0.        ]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [ ]:
x['sex']=lb.fit_transform(x['sex'])
x['smoker']=lb.fit_transform(x['smoker'])
x['region']=lb.fit_transform(x['region'])

In [ ]:
x

age  sex     bmi  children  smoker  region
0      19    0  27.900         0       1       3
1      18    1  33.770         1       0       2
2      28    1  33.000         3       0       2
3      33    1  22.705         0       0       1
4      32    1  28.880         0       0       1
...   ...  ...     ...       ...     ...     ...
1333   50    1  30.970         3       0       1
1334   18    0  31.920         0       0       0
1335   18    0  36.850         0       0       2
1336   21    0  25.800         0       0       3
1337   61    0  29.070         0       1       1

[1338 rows x 6 columns]

In [ ]:
log_transform=FunctionTransformer(np.log1p)
#apply the transformation to the dataset
x_transformed=log_transform.transform(x)
print(x_transformed)

           age       sex       bmi  children    smoker    region
0     2.995732  0.000000  3.363842  0.000000  0.693147  1.386294
1     2.944439  0.693147  3.548755  0.693147  0.000000  1.098612
2     3.367296  0.693147  3.526361  1.386294  0.000000  1.098612
3     3.526361  0.693147  3.165686  0.000000  0.000000  0.693147
4     3.496508  0.693147  3.397189  0.000000  0.000000  0.693147
...        ...       ...       ...       ...       ...       ...
1333  3.931826  0.693147  3.464798  1.386294  0.000000  0.693147
1334  2.944439  0.000000  3.494080  0.000000  0.000000  0.000000
1335  2.944439  0.000000  3.633631  0.000000  0.000000  1.098612
1336  3.091042  0.000000  3.288402  0.000000  0.000000  1.386294
1337  4.127134  0.000000  3.403528  0.000000  0.693147  0.693147

[1338 rows x 6 columns]


In [ ]:
df=x_transformed

In [ ]:
df

age       sex       bmi  children    smoker    region
0     2.995732  0.000000  3.363842  0.000000  0.693147  1.386294
1     2.944439  0.693147  3.548755  0.693147  0.000000  1.098612
2     3.367296  0.693147  3.526361  1.386294  0.000000  1.098612
3     3.526361  0.693147  3.165686  0.000000  0.000000  0.693147
4     3.496508  0.693147  3.397189  0.000000  0.000000  0.693147
...        ...       ...       ...       ...       ...       ...
1333  3.931826  0.693147  3.464798  1.386294  0.000000  0.693147
1334  2.944439  0.000000  3.494080  0.000000  0.000000  0.000000
1335  2.944439  0.000000  3.633631  0.000000  0.000000  1.098612
1336  3.091042  0.000000  3.288402  0.000000  0.000000  1.386294
1337  4.127134  0.000000  3.403528  0.000000  0.693147  0.693147

[1338 rows x 6 columns]