In [ ]:
import numpy as np

In [ ]:
a=[1,45,78,98]
type(a)

list

In [ ]:
b=np.array(a)
b

array([ 1, 45, 78, 98])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
a=[]
size=int(input("enter size:"))
for i in range(size):
  val=int(input("enter value:"))
  a.append(val)
#print(a)
b=np.array(a)
print(b)
type(b)


enter size:3
enter value:34
enter value:45
enter value:56
[34 45 56]


numpy.ndarray

In [ ]:
a=[1,2,3],[4,5,6],[7,8,9]
#a
b=np.array(a)
#b
print("total rows and column",b.shape)
print("total elements",b.size)
b=np.array(a)
b

total rows and column (3, 3)
total elements 9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=[1,2,3,10],[4,5,6,11],[7,8,9,12]
#a
b=np.array(a)
#b
print("total rows and column",b.shape)
print("total elements",b.size)
b=np.array(a)
b

total rows and column (3, 4)
total elements 12


array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [ ]:
a=np.array([1,3,4])
a
a.ndim


1

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a=np.array([[[1,2,3],[4,5,6]]])
a


array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
a.ndim

3

In [ ]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a=np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a=np.ones(3)
a

array([1., 1., 1.])

In [ ]:
a=np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#(3) eye()=it will create an array in which diagonal positional elements will be
#1 and rest all are 0

In [ ]:
a=np.eye(3)  # rows==columns   symmatric matrics
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.eye(3,4)   #rows!=column   Asymmatric matrics
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#(4). diag()=it will create an array in which e can set our custom values at diagonal position

In [ ]:
a=np.diag([1,34,67,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [ ]:
#(s) random module
#(a) randint   it will create an array randomly in a give range
#syntax: np.random.randint(min_range,max_range,total_numbers)

In [ ]:
a=np.random.randint(1,10,13)
a


array([9, 4, 2, 5, 7, 7, 5, 7, 3, 9, 1, 7, 4])

In [ ]:
#(b) rand()  it will genrate random number from 0-1
#syntax:  np.random.rand(total_random_number)


In [ ]:
a=np.random.rand(4)
a

array([0.82600169, 0.84198615, 0.59147108, 0.38806638])

In [ ]:
#(c)
#data set (emp.data)(emp-id,salary,domain)  randomly column add(working hours)

In [ ]:
#(c)
#syntax:
#np.random.seed(45)
#a=np.random.randint(1,10,2)

In [ ]:
np.random.seed(45)
a=np.random.randint(1,10,3)
a

array([4, 1, 6])

In [ ]:
# view as copy

In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
b=a[1:4]
b[:]=0
b


array([0, 0, 0])

In [ ]:
a

array([10,  0,  0,  0, 50, 60, 70, 80])

In [ ]:
#copy

In [ ]:
a=np.array([10, 20, 30, 40, 50, 60, 70, 80])
b=a[1:4].copy()
b[:]=0
b

array([0, 0, 0])

In [ ]:
#reshaping the array
#totl rows*columns=total_elements

In [ ]:
a=np.random.randint(1,50,12)
a

array([36,  5, 16,  2, 15,  9, 24, 47,  9, 13, 35, 25])

In [ ]:
#1*12  12*1
#6*2   2*6
#3*4   4*3

In [ ]:
a.reshape(2,6)

array([[36,  5, 16,  2, 15,  9],
       [24, 47,  9, 13, 35, 25]])

In [ ]:
a.reshape(3,4)

array([[36,  5, 16,  2],
       [15,  9, 24, 47],
       [ 9, 13, 35, 25]])

In [ ]:
#a.reshape(6,3)

In [ ]:
#y=mx+b
#m=matrics   weight
#x=values   matrics
#matrics(column)*(row)matrics

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(-1,3)

array([[36,  5, 16],
       [ 2, 15,  9],
       [24, 47,  9],
       [13, 35, 25]])

In [ ]:
a.reshape(2,-1)

array([[36,  5, 16,  2, 15,  9],
       [24, 47,  9, 13, 35, 25]])

In [ ]:
# operations on array

In [ ]:
a=np.arange(1,5,2)
a

array([1, 3])

In [ ]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [ ]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a.dot(b)  #1*5+2*7

array([[19, 22],
       [43, 50]])

In [ ]:
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [ ]:

b=a>10
a[b]

array([11, 12, 13, 14])

In [ ]:
a=np.arange(1,4)
a**2

array([1, 4, 9])

In [ ]:
a**3

array([ 1,  8, 27])

In [ ]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(a)


np.int64(45)

In [ ]:
np.sum(a,axis=1) # axis=1 means rows wise operation

array([ 6, 15, 24])

In [ ]:
np.sum(a,axis=0) # axis=0 means column wise operation

array([12, 15, 18])

In [ ]:
#unique() it wil create an array in which it will remove duplicates values and
#it will return 3 array
#arr unique elements of array
#return_index = true   indexing of unique element
#return_count = true  frequency of each unique element


In [ ]:
a=np.array([1,2,3,1,1,1,1,4,5,4,4,4,4,4,4,6,7])
a

array([1, 2, 3, 1, 1, 1, 1, 4, 5, 4, 4, 4, 4, 4, 4, 6, 7])

In [ ]:
b=np.unique(a,return_index=True,return_counts=True)
b

(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  2,  7,  8, 15, 16]),
 array([5, 1, 1, 7, 1, 1, 1]))

In [ ]:
#linspace()  it will return an array in which elements will be same gap in a give range
#syntax  np.linespace(min_num,max_num,total_numbers)

In [ ]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
#horizontal and vertical stacking
#horizontal stacking it wil add 2 or more arrays in horizontally

In [ ]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [ ]:
c=np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [ ]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a=np.random.randint(1,50,10)
print(a)

[13 18 39  5 47 31 15 43 37 32]
