TEXT REPRESENTATION

In [ ]:
# 1 bag of words
# we use conivectoriztion

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame({'text':['people wacth cricket','player was player',
                         'people write comment',
                         'cricket play comment'],'output':[1,1,0,0]})

In [ ]:
df

,text,output
0,people wacth cricket,1
1,player was player,1
2,people write comment,0
3,cricket play comment,0


In [ ]:
# people watch cricket player was written comment play
# []
# []
# []
# []

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer()

In [ ]:
bow=cv.fit_transform(df['text'])

In [ ]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'wacth': 5, 'cricket': 1, 'player': 4, 'was': 6, 'write': 7, 'comment': 0, 'play': 3}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 1 0 0]]
[[0 0 0 0 2 0 1 0]]


In [ ]:
cv.transform(['cricket watch and write comment of cricket comment']).toarray()

array([[2, 2, 0, 0, 0, 0, 0, 1]])

In [ ]:
# 2

In [ ]:
v=CountVectorizer(ngram_range=(1,2))
# v=CountVectorizer(ngram_range=(2,2))

In [ ]:
bow=v.fit_transform(df['text'])

In [ ]:
df['text']

,text
0,people wacth cricket
1,player was player
2,people write comment
3,cricket play comment


In [ ]:
print(v.vocabulary_)

{'people': 3, 'wacth': 10, 'cricket': 1, 'people wacth': 4, 'wacth cricket': 11, 'player': 8, 'was': 12, 'player was': 9, 'was player': 13, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


In [ ]:
# TF(Term Frequency)
# IDF(Inverse Document Frequency)

In [ ]:
# TF(t,d) = (number of occurences of term t in document s)/
# (Total number ofterms in the document d)
# example==>
# d1=people watch cricket.
# tf(people,d1)=1/3

# d1=match was match.
# tf(match,d1)=2/3


In [ ]:
#  IDF(t)=loge(toatal number of documents in the corpus)/
# (number of documents with term t in them)
# here corpus means  number of sentences

#example==>
# d1='people wacth cricket'
# d2='player was player'
# d3=people write comment
# d4='cricket play comment'
# Idf(cricket)=log(4/4)
# Idf(people)=log(4/2)

In [ ]:
# we can use this by apply feature_extraction method in sklearn

In [ ]:
df

,text,output
0,people wacth cricket,1
1,player was player,1
2,people write comment,0
3,cricket play comment,0


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.66767854, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.        , 0.4472136 , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [ ]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'wacth' 'was' 'write']


In [ ]:
import pandas as pd
import re
import string
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df = pd.read_csv(
    "/content/IMDB Dataset - IMDB Dataset.csv",
    encoding='utf-8',
    engine='python',
    on_bad_lines='skip'
)

# Take top 50 rows
df = df.head(50)

In [ ]:
# -----------------------------------
# Text Cleaning Functions
# -----------------------------------

# Lowercase
df['review'] = df['review'].str.lower()


In [ ]:
# Remove HTML tags
import re
def remove_html_tags(text):
  Pattern=re.compile('<.*?>')
  return Pattern.sub(r'',text)

In [ ]:
text="<html><body><p> m=Movie1 </p> Click here to <a heref='http://goggle.com'>download/a"

In [ ]:
remove_html_tags(text)

' m=Movie1  Click here to download/a'

In [ ]:
df['review'] = df['review'].apply(remove_html_tags)

In [ ]:
# Remove URLs
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub('', text)

In [ ]:
text4='for notebook click http://www.deture.com/delta/note1234acc'

In [ ]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
# Remove punctuation
exclude = string.punctuation

In [ ]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char,'')
    return text

In [ ]:
text3='string.with.punctuation?'

In [ ]:
remove_punc(text3)

'string.with.punctuation?'

In [ ]:
df['review']=df['review'].apply(remove_punc)

In [ ]:
df

,review,sentiment
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production. the filming tec...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive
5,"probably my all-time favorite movie, a story o...",positive
6,i sure would like to see a resurrection of a u...,positive
7,"this show was an amazing, fresh & innovative i...",negative
8,encouraged by the positive comments about this...,negative
9,if you like original gut wrenching laughter yo...,positive


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['review']).toarray()

array([[0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       ...,
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.084815, ..., 0.      , 0.      , 0.      ]])

In [ ]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[4.23867845 4.23867845 2.73460106 ... 4.23867845 4.23867845 4.23867845]
['00' '000' '10' ... 'zellweger' 'zombie' 'zwick']
